name: Node.js CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  # -----------------------------
  # Job 1: Test Node.js
  # -----------------------------
  test:
    name: Test Node.js Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Check application
        run: node --check src/server.js

      - name: Check application files
        run: |
          test -f src/app.js
          test -f src/server.js
          test -f src/routes/health.routes.js
          test -f src/controllers/health.controller.js

  # -----------------------------
  # Job 2: Build and Push Docker
  # -----------------------------
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate GitHub Actions with AWS using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::060795914141:role/GitHubActionsECRRole
          aws-region: ap-south-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker image
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devops-node-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      # Push Docker image
      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devops-node-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Display pushed image
      - name: Display image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devops-node-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Docker image pushed successfully:"
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"